sources:
  - name: CloudflareAPI
    handler:
      openapi:
        source: openapi.json
        operationHeaders: 
          Authorization: "{context.headers.authorization}"

plugins:
  - responseCache:
      ttlPerCoordinate:
        - coordinate: Query.*
          ttl: 3600

cache:
  cfwKv:
    namespace: MESH

