name: CI
on: [pull_request, push]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

